### PR TITLE
Removes runStatus check, fixes some logic

### PR DESCRIPTION
**Pull request by AndreasVerhoeven**
- This fixes an issue where the OpenAPI would not return the undocumented `runStatus` flag, which caused the plugin to query the OpenAPI continuously. Unfortunately, the **moving** flag is incorrectly missing from the API, so we have no way to detect if we're moving and thus the plugin doesn't update HomeKit correctly: it assumes that the blind tilt has stopped moving.

- This works around a crasher in the OpenAPI where sending `down;0` would return an error response, resulting in the plugin continuously querying its position and thus getting rate limited for a day. Workaround is to send `closeDown` for `down;0` instead. Also sends `closeUp` and `fullyOpen` for the relevant cases.

- Fixes an issue with `use_tilt_for_direction` not working correctly

@donavanbecker 

Due to bugs in the OpenAPI, the plugin could hit its rate limit: when the tilt (and curtain!) are moving the plugin keeps querying the OpenAPI to update HomeKit. When something goes wrong, the querying is never stopped tho. It might be a good idea to add an internal rate-limiter somewhere in the plugin. E.g. after querying more than 60s for changes, we stop querying anyways and assume something went wrong. What do you think?

### CODE REVIEW

**Comment by donavanbecker** [comment]
@AndreasVerhoeven I like the idea!!

I am going to merge and then if you bring another PR with that enhancement, we can merge that PR.

No wonder I was hitting my rate limit.......

**Comment by donavanbecker** [comment]
Also thanks for all of these enhancements.

**Comment by donavanbecker** [comment]
@AndreasVerhoeven Are you on the Homebridge discord server?

**Comment by AndreasVerhoeven** [comment]
> @AndreasVerhoeven Are you on the Homebridge discord server?

I've never used discord, so no :) Would it help with development?

**Comment by donavanbecker** [comment]
It could. It is designed for users and developers.

Main reason I asked is because then we could communicate off GitHub, about about changes..

**Comment by AndreasVerhoeven** [comment]
> It could. It is designed for users and developers.
> 
> Main reason I asked is because then we could communicate off GitHub, about about changes..

Just signed up and joined switchbot-channel !

**Pull request merged**
