### PR TITLE
Fixes #310 "Other" IR Devices send commandOn and commandOff at reversed times

### LINKED ISSUE #310: Bug: "Other" IR Devices send commandOn and commandOff at reversed times
### Describe The Bug

When turning on a device, it sends commandOff, and vice versa

### To Reproduce

Set up an IR "Other" device and try toggling state.

### Expected behavior

Turning on a device should use the configured commandOn command, not commandOff

### Relevant log output

```shell
(When turning a device off)

[12/04/2022, 15:31:22] [SwitchBot] [DEBUG] Other: Iceman On: 0
[12/04/2022, 15:31:22] [SwitchBot] Other: Iceman Sending request to SwitchBot API. command: On, parameter: default, commandType: customize
[12/04/2022, 15:31:23] [SwitchBot] [DEBUG] Other: Iceman pushChanges: [object Object]
[12/04/2022, 15:31:23] [SwitchBot] [DEBUG] Other: Iceman Command successfully sent.
[12/04/2022, 15:31:23] [SwitchBot] [DEBUG] Other: Iceman updateCharacteristic Active: 1
```

### Config for homebridge-switchbot

```shell
{
    "deviceId": "xxxxxxxxx",
    "configRemoteType": "Fan",
    "other": {
        "deviceType": "Fan",
        "commandOff": "Off",
        "commandOn": "On"
    },
        "logging": "debug"
}
```

### Screenshots

_No response_

### Device & Model

Raspberry Pi 3

### Node.js Version

v16.13.0

### NPM Version

v8.1.0

### Homebridge Version

v1.4.0

### Homebridge Switchbot Plugin Version

v1.12.8

### Homebridge Config UI X Plugin Version

v4.42.0

### Operating System

Raspbian

### PR DESCRIPTION
**Pull request by jonzhan**
As far as I can tell this fix makes sense but I have no idea how to test it on my local setup, sorry.

### CODE REVIEW

**Comment by donavanbecker** [comment]
I have pushed this to beta. you can test this on the latest beta version and let me know if it works for you?

**Comment by jonzhan** [comment]
Thank you, I can confirm that this works on v1.12.9-beta.23!

**Comment by donavanbecker** [comment]
@jonzhan awesome! I will release and update soon

**Comment by jonzhan** [comment]
Great. Thank you!

**Comment by jonzhan** [comment]
@donavanbecker I found another related bug (close enough that I don't think it needs another issue) - right now the code assumes that any instruction is a toggle of the device's state, so it works fine with simple switches but may send the wrong signal when using scenes.

I can cook up a fix, but I would like to ask for your input on what the desired behavior should be. 

If, for example, a device is already "off" and a scene tries to turn the device off again, would you prefer that:

1. an "off" IR signal should be sent anyway
2. nothing should be done

**Comment by donavanbecker** [comment]
I guess we could make a config that would say do you want 1 or do you want 2 then users can choose.

**Comment by jonzhan** [comment]
It’s certainly an option! Have you received feedback from other users who would prefer the “always transmit” functionality instead?

**Comment by donavanbecker** [comment]
Yes I have. I actually have a config called allow push for one of the other devices. But it's a SwitchBot device not Ir, so might as well add it. So we do not send, and only send when `allowPush` is yes in config.

**Comment by donavanbecker** [comment]
@jonzhan if you wanna put a PR together. I will ad the `allowPush` config

**Comment by jonzhan** [comment]
@donavanbecker Sounds good. I'll get a PR over in a day or so!

**Comment by donavanbecker** [comment]
No rush. Also have you upgraded to v2.0.0?

**Comment by jonzhan** [comment]
Ooh no, I didn’t realize there was a point release. Nice! Good to have the BLE fallback.

**Comment by donavanbecker** [comment]
that was always there before but kinda changed things up on it.

**Comment by jonzhan** [comment]
I upgraded to 2.0 but unfortunately it has broken my IR devices, whoops! I'll make a separate ticket and circle back to this after that's figured out.

**Comment by donavanbecker** [comment]
@jonzhan V2.1.0 should have fixed that?

**Comment by jonzhan** [comment]
hmm unfortunately not - I have also tried v2.1.1-beta.0 with no luck!

**Comment by donavanbecker** [comment]
@jonzhan sorry. Okay once you open the ticket I will take a look.

**Comment by jonzhan** [comment]
No worries, wonder what it is! Created #520

**Comment by jonzhan** [comment]
I've made a bunch of changes to support `allowPush` in [this PR](https://github.com/OpenWonderLabs/homebridge-switchbot/pull/529) - I inferred the necessary properties and logic based on [the allowPush implementation in bot.ts](https://github.com/OpenWonderLabs/homebridge-switchbot/blob/c582a86aae859fe9654f243c4e3c7c2ccb7b6cb8/src/device/bot.ts#L585), but I think it's correct.

**Comment by donavanbecker** [comment]
Okay latest beta should have the right change... I think.

**Pull request merged**
