### PR TITLE
fix: Improve debug log in BLE connection

### PR DESCRIPTION
**Pull request by anzmin**
## :recycle: Current situation

I have a slight problem with the log of the connectBLE function (in platform.ts). The `this.switchBotBLE` object is wrapped in a template literal in JS, so the output of that log is `[object Object]`. 

image

## :bulb: Proposed solution

 Wrap the `this.switchBotBLE` object in 'JSON.stringify' to inspect it in more detail

### CODE REVIEW

**Comment by donavanbecker** [comment]
This change, causes this issue:
image

**Comment by anzmin** [comment]
@donavanbecker 
The class this.switchBotBLE is too big, so when stringifying it, a circular reference occurs. To work around this, you can log only the necessary information in the log, such as `${device.deviceType}: ${accessory.displayName} 'node-switchbot' found!` or using a stringify library that prevents circular references. Which one looks better?

**Comment by donavanbecker** [comment]
I already fixed doing it a different way. If you look at the last commit in the beta branch.

**Comment by anzmin** [comment]
Thank you!

**Pull request merged**
