### PR TITLE
MQTT support for meter and curtain devices.

### PR DESCRIPTION
**Pull request by banboobee**
Hi donavanbecker

This PR implements MQTT advertisement functions for the characteristics of meter and curtain devices inspired by the discussion of #303.

Configurations:
1. Ths function is enabled by "mqttURL" config keywords of "devices", and open MQTT connection if specified.
2. The options (**) for the MQTT connection can be specified through the "mqttOptions" config keywords of "devices".
3. The options (**) for the MQTT publishing can be specified through the "mqttPubOptions" config keywords of "devices".
** See mqtt.js(https://github.com/mqttjs/MQTT.js.git) for the details.

e.g.  { "deviceId": "xxxxxxxxxxxx",  "configDeviceType": "Meter", "mqttURL": "mqtt://localhost", "mqttPubOptions": {"retain": true}}

Topic and Message:
a. MQTT topic for meter devices are following format.
        "homebridge-switchbot/meter/xx:xx:xx:xx:xx:xx"
        where xx:xx:xx:xx:xx:xx is the BLE mac address of device.
    and MQTT message for the topics are advertised in a following format.
        {"temperature": x, "humidity"; y, "battery": z, "lowBattery":t }
        where x, y, z are the numeric values and t is true or false of the keys.

b. MQTT topic for the curtain devices are following format for each of characteristic CHARACTERISTIC. 
        "homebridge-switchbot/curtain/xx:xx:xx:xx:xx:xx/CHARACTERISTIC"
        where xx:xx:xx:xx:xx:xx is the BLE mac address of device.
        CHARACTERISTIC is one of "CurrentPosition", "PositionState", "TargetPosition", "CurrentAmbientLightLevel".
    and MQTT message for each topic is its numeric value.

I'm happy if this PR will be the reference for your development.

### CODE REVIEW

**Comment by donavanbecker** [comment]
Please rebase your beta branch. Then I will get a new version out after testing

**Comment by banboobee** [comment]
OK. Rebased to your beta branch, and target branch of this PR is also updated to the beta.

**Comment by donavanbecker** [comment]
Have some conflicts that need to be resolved it looks like.

**Comment by banboobee** [comment]
I see. You integrated another PR, Resolved them.

**Comment by donavanbecker** [comment]
@banboobee, oh sorry, dependencies automerge, that is what looks like happened. Thanks!

**Comment by donavanbecker** [comment]
implemented into the latest beta. can you test and let me know? as I don't use this.

**Comment by banboobee** [comment]
Sure, I will.

**Comment by banboobee** [comment]
Hi donavanbecker

I checked the functions with 4 meters and 1 curtain, and found no issues.
EVE history graphs can be seen for 3 meter devices with "history": true.
MQTT advertisements of meters and curtain devices with "mqttURL" also confirmed with MQTT explorer.

I am very appreciate for your prompt responses.

Thank you very much.

Tsted confuguration: 
        {
            "name": "SwitchBot",
            "credentials": {
                "openToken": "....",
                "notice": "Keep your token a secret!"
            },
            "options": {
                "devices": [
                    {
                        "deviceId": ",,,",
                        "configDeviceName": "switchbot-curtain@living",
                        "configDeviceType": "Curtain",
			"mqttURL": "mqtt://localhost",
			"curtain": {
			    "set_min": 15,
			    "set_max": 85
			},
                        "mqttPubOptions": {
                            "retain": true
                        }
                    },
                    {
                        "deviceId": "....",
                        "configDeviceName": "switchbot@bedroom",
                        "configDeviceType": "Meter",
                        "ble": true,
                        "scanDuration": 10,
                        "mqttURL": "mqtt://localhost",
                        "mqttPubOptions": {
                            "retain": true
                        },
                        "history": true
                    },
                    {
                        "deviceId": "....",
                        "configDeviceName": "switchbot@kitchen",
                        "configDeviceType": "Meter",
                        "ble": true,
                        "scanDuration": 10,
                        "mqttURL": "mqtt://localhost",
                        "mqttPubOptions": {
                            "retain": true
                        },
                        "history": true
                    },
                    {
                        "deviceId": "....",
                        "configDeviceName": "switchbot@guestroom",
                        "configDeviceType": "Meter",
                        "ble": true,
                        "scanDuration": 10
                    },
                    {
                        "deviceId": "....",
                        "configDeviceName": "switchbot@living",
                        "configDeviceType": "Meter",
                        "mqttURL": "mqtt://localhost",
                        "mqttPubOptions": {
                            "retain": true
                        },
                        "history": true
                    }
                ]
            },
            "platform": "SwitchBot"
        },

**Comment by Aekung** [comment]
Hello,

I followed the instruction but my mqtt server requires authorization. Are there anywhere I can set my mqtt server credential for this to work?

Thank you and looking forward to hearing from you.

PS. The log is now throwing this error

`[06/05/2022, 20:47:19] [SwitchBot] Meter: Indoor Garden Hygrometer Failed to establish MQTT connection. Error: Connection refused: Not authorized`

**Pull request merged**
