### PR TITLE
Add Battery level for Meter Plus #781 #782

### PR DESCRIPTION
**Pull request by mrlt8**
Similar to #782 but for the Meter Plus. 

Note: I do not have a meter plus device to test.

### CODE REVIEW

**Review by donavanbecker — APPROVED** [review]

**Comment by donavanbecker** [comment]
I am going to revert this as it doesn't look like the Meter Plus API supports this.

```
[@switchbot/homebridge-switchbot] This plugin generated a warning from the characteristic 'Battery Level': characteristic value expected valid finite number and received "NaN" (number). See https://homebridge.io/w/JtMGR for more info.
```

**Comment by mrlt8** [comment]
API documentation seems to show that the meter plus supports the battery level: https://github.com/OpenWonderLabs/SwitchBotAPI#meter-plus-1

**Comment by donavanbecker** [comment]
weird because my API is showing too. Okay I am going to re-revert and look into this.

```
{"statusCode":100,"body":{"deviceId":"XXXXXXXXXXX","deviceType":"MeterPlus","hubDeviceId":"XXXXXXXXXXX","humidity":85,"temperature":22.2,"version":"V0.5","battery":50},"message":"success"}
```

**Comment by mrlt8** [comment]
My bad. I didn't realize the OpenAPI battery was using `this.Battery` and BLE was using `this.battery`.

**Pull request merged**
