### PR TITLE
Eve history features for meter devices.

### PR DESCRIPTION
**Pull request by banboobee**
Hi donavanbecker

This PR adds temperature/humidity logging features for meter devices to see their graphical history representation in EVE app.
 

Configurations:

This function is enabled by specifying true for "history" config keywords of "devices", and create following logging file 
under user.storagePath() if enabled. i.e. { "configDeviceType": "Meter", ... ,"history": true}

HOSTNAME_xx:xx:xx:xx:xx:xx_persist.json.json

where HOSTNAME is a hostname and xx:xx:xx:xx:xx:xx is a BLE mac address of the meter device.

The file records average values of temperature and humidity for every 10 minutes and EVE app shows their graphical representations.

This function is essential for my use case of homekit and hope to be integrated in your plug-in.

Thanks in advance.

### CODE REVIEW

**Comment by donavanbecker** [comment]
Please rebase your beta branch. Then I will get a new version out after testing

**Comment by banboobee** [comment]
OK. Rebased to your beta branch, and target branch of this PR is also updated to the beta.

**Comment by donavanbecker** [comment]
implemented into the latest beta. can you test and let me know? as I don't use this.

**Comment by banboobee** [comment]
Sure, I will.

**Comment by banboobee** [comment]
Hi donavanbecker

I checked the functions with 4 meters and 1 curtain, and found no issues.
EVE history graphs can be seen for 3 meter devices with "history": true.
MQTT advertisements of meters and curtain devices with "mqttURL" also confirmed with MQTT explorer.

I am very appreciate for your prompt responses.

Thank you very much.

Tsted confuguration: 
        {
            "name": "SwitchBot",
            "credentials": {
                "openToken": "....",
                "notice": "Keep your token a secret!"
            },
            "options": {
                "devices": [
                    {
                        "deviceId": ",,,",
                        "configDeviceName": "switchbot-curtain@living",
                        "configDeviceType": "Curtain",
			"mqttURL": "mqtt://localhost",
			"curtain": {
			    "set_min": 15,
			    "set_max": 85
			},
                        "mqttPubOptions": {
                            "retain": true
                        }
                    },
                    {
                        "deviceId": ",,,",
                        "configDeviceName": "switchbot@bedroom",
                        "configDeviceType": "Meter",
                        "ble": true,
                        "scanDuration": 10,
                        "mqttURL": "mqtt://localhost",
                        "mqttPubOptions": {
                            "retain": true
                        },
                        "history": true
                    },
                    {
                        "deviceId": ",,,",
                        "configDeviceName": "switchbot@kitchen",
                        "configDeviceType": "Meter",
                        "ble": true,
                        "scanDuration": 10,
                        "mqttURL": "mqtt://localhost",
                        "mqttPubOptions": {
                            "retain": true
                        },
                        "history": true
                    },
                    {
                        "deviceId": ",,,",
                        "configDeviceName": "switchbot@guestroom",
                        "configDeviceType": "Meter",
                        "ble": true,
                        "scanDuration": 10
                    },
                    {
                        "deviceId": ",,,",
                        "configDeviceName": "switchbot@living",
                        "configDeviceType": "Meter",
                        "mqttURL": "mqtt://localhost",
                        "mqttPubOptions": {
                            "retain": true
                        },
                        "history": true
                    }
                ]
            },
            "platform": "SwitchBot"
        },

**Pull request merged**
