### PR TITLE
Throw error on unknown status code from API 

### PR DESCRIPTION
**Pull request by mrlt8**
This will only throw an error if the server returns an unknown status code. I'm wondering if it should throw an error on any status code that does not equal `100` or `200` or maybe just codes >200?

### CODE REVIEW

**Comment by donavanbecker** [comment]
Yeah that would work.

**Comment by mrlt8** [comment]
@donavanbecker I'm not really sure about the `apiError` method that gets called on an error.  It attempts to `updateCharacteristic` but will usually fail?
```
This plugin generated a warning from the characteristic 'Active': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.
```

**Comment by donavanbecker** [comment]
@mrlt8 I attempted to use that before and couldn't figure it out. It might be just easier to leave what I have?

**Comment by donavanbecker** [comment]
Sorry @mrlt8, can you open a new pr and point it to `nextVersion` branch?

**Pull request closed without merging**
